version: '3.8'

services:

  database:
    container_name: postg
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_DB=shopdb
      - POSTGRES_USER=yesterday
      - POSTGRES_PASSWORD=deadover*20
    ports:
      - "5432:5432"
    volumes:
      - datenbank:/var/lib/postgresql/data

  server:
    container_name: django
    build:
      context: ./server
    command: [ "bash", "entrypoint.sh" ]
    depends_on:
      - database
    environment:
      - SQL_ENGINE=django.db.backends.postgis
      - SQL_DATABASE=shopdb
      - SQL_USER=yesterday
      - SQL_PASSWORD=deadover*20
      - SQL_HOST=ghost
      - SQL_PORT=5432
    ports:
      - 8004:8000
    volumes:
      - ./server:/usr/src/app

volumes:
  datenbank:
